"""Add phone sensor support - DeviceType, data_source, activity tracking

Revision ID: b52623274ba1
Revises: 
Create Date: 2026-01-21 12:49:16.774742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52623274ba1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.Enum('IOT_HARDWARE', 'MOBILE_APP', 'WEARABLE', 'MANUAL', name='devicetype'), nullable=True))
    op.add_column('devices', sa.Column('phone_model', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('phone_os', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('sensor_capabilities', sa.JSON(), nullable=True))
    op.add_column('vital_signs', sa.Column('data_source', sa.Enum('IOT_HARDWARE', 'MOBILE_APP', 'WEARABLE', 'MANUAL', name='devicetype'), nullable=True))
    op.add_column('vital_signs', sa.Column('sensor_accuracy', sa.Float(), nullable=True))
    op.add_column('vital_signs', sa.Column('activity_context', sa.String(), nullable=True))
    op.add_column('vital_signs', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('vital_signs', sa.Column('location_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vital_signs', 'location_lng')
    op.drop_column('vital_signs', 'location_lat')
    op.drop_column('vital_signs', 'activity_context')
    op.drop_column('vital_signs', 'sensor_accuracy')
    op.drop_column('vital_signs', 'data_source')
    op.drop_column('devices', 'sensor_capabilities')
    op.drop_column('devices', 'phone_os')
    op.drop_column('devices', 'phone_model')
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###
